## Aplicación Teorema de Bayes

Caso: en la fiesta de cumpleaños de Julián, quien cumplía 7 años, su padre tiene tres grandes bolsas repletas de golosinas. En la primera bolsa, había 20 picos dulces, 50 chupetines, 30 chocolates. En la segunda bolsa había 60 picos dulces, 30 chocolates y 10 chupetines mientras que en la tercera y última bolsa, habían 60 chocolates, 30 picos dulces y 10 chupetines. 

Ejercicio: 

1. Usando bayes, calcular la probabilidad de sacar picos dulces de la bolsa 1,2,3
2. Usando bayes, calcular la probabilidad de sacar chupetines de la bolsa 1,2,3
3. Usando bayes, calcular la probabilidad de sacar chocolates de la bolsa 1,2,3

In [7]:
import numpy as np

#Respuesta 1: probabilidad de sacar picos dulces

def bayes(bosas, porcentajes):
    marg = sum(np.multiply(bolsas, porcentajes))
    post = np.divide(np.multiply(bolsas, porcentajes), marg)
    return post
bolsas = [1/3, 1/3, 1/3]
porcentajes = [0.2, 0.6,0.3]

bayes(bolsas,porcentajes)

array([0.18181818, 0.54545455, 0.27272727])

In [8]:
print("En la primera bolsa, hay una probabilidad del 33% que saque picos dulces")
print("En la segunda bolsa, hay una probabilidad del 54% que saque picos dulces")
print("En la tercera bolsa, hay una probabilidad del 27% que saque picos dulces")

En la primera bolsa, hay una probabilidad del 33% que saque picos dulces
En la segunda bolsa, hay una probabilidad del 54% que saque picos dulces
En la tercera bolsa, hay una probabilidad del 27% que saque picos dulces


In [9]:
#Respuesta2: probabilidad de sacar chupetines 

bolsas = [1/3, 1/3, 1/3]
porcentajes = [0.5, 0.1 ,0.1]

bayes(bolsas,porcentajes)

array([0.71428571, 0.14285714, 0.14285714])

In [11]:
print("En la primera bolsa, hay una probabilidad del 71% que saque chupetines")
print("En la segunda bolsa, hay una probabilidad del 14% que saque chupetines")
print("En la tercera bolsa, hay una probabilidad del 14% que saque chupetines")

En la primera bolsa, hay una probabilidad del 71% que saque chupetines
En la segunda bolsa, hay una probabilidad del 14% que saque chupetines
En la tercera bolsa, hay una probabilidad del 14% que saque chupetines


In [14]:
#Respuesta3: probabilidadd de sacar chocolates

bolsas = [1/3, 1/3, 1/3]
porcentajes = [0.3, 0.3,0.6]

bayes(bolsas,porcentajes)

array([0.25, 0.25, 0.5 ])

In [15]:
print("En la primera bolsa, hay una probabilidad del 25% que saque chocolates")
print("En la segunda bolsa, hay una probabilidad del 25% que saque chocolates")
print("En la tercera bolsa, hay una probabilidad del 50% que saque chocolates")

En la primera bolsa, hay una probabilidad del 25% que saque chocolates
En la segunda bolsa, hay una probabilidad del 25% que saque chocolates
En la tercera bolsa, hay una probabilidad del 50% que saque chocolates
